// Code generated by Cored SDK Generator. DO NOT EDIT.
import type { Int64 } from '@/core/types';

/** Send a message (Request) */
export interface SendMessageReq {
  message_type?: string; // Message type
  message_content?: MessageContent; // Message content
  chat_id?: string; // Chat ID
  reply_message_id?: string; // ID of the message being replied to
}

/** Send a message (Response) */
export interface SendMessageResp {
  message_id?: string; // Message ID
}

/** Get a message (Request) */
export interface GetMessageReq {
  message_id?: string; // Message ID
}

/** Get a message (Response) */
export interface GetMessageResp {
  message?: Message; // Message
}

/** Recall a message (Request) */
export interface RecallMessageReq {
  message_id?: string; // Message ID
}

/** Recall a message (Response) */
export interface RecallMessageResp {
}

/** Mark message as read (Request) */
export interface ReadMessageReq {
  message_id?: string; // Message ID
}

/** Mark message as read (Response) */
export interface ReadMessageResp {
}

/** Message content */
export interface MessageContent {
  text?: MessageText; // Text message
  image?: MessageImage; // Image message
  sticker?: MessageSticker; // Sticker message
  video?: MessageVideo; // Video message
  audio?: MessageAudio; // Audio message
  file?: MessageFile; // File message
  user_card?: MessageUserCard; // User card message
  group_card?: MessageGroupCard; // Group card message
  group_announcement?: MessageGroupAnnouncement; // Group announcement
  card?: MessageCard; // Card message
}

/** Text message */
export interface MessageText {
  content?: string; // Content
  attachment_list?: MessageTextAttachment[]; // Attachment list, referenced in content as {{attach:id}}
  mention_user_list?: MessageTextMentionUser[]; // Mentioned user list, referenced in content as {{mention:user_id}}. Use user_id "all" to mention everyone
  emoji_list?: MessageTextEmoji[]; // Emoji list, referenced in content as {{emoji:emoji_id}}
}

/** Attachment */
export interface MessageTextAttachment {
  attachment_id?: string; // Attachment ID, referenced in content as {{id}}, defined by the client
  attachment_type?: string; // Attachment type
  attachment_content?: MessageTextAttachmentContent; // Attachment content
}

/** Attachment content */
export interface MessageTextAttachmentContent {
  image?: FileImage; // Image
}

/** Image file */
export interface FileImage {
  image?: File; // Image, max width/height 1024
  image_width?: Int64; // Image width
  image_height?: Int64; // Image height
  image_origin?: File; // Original image
  image_origin_width?: Int64; // Original image width
  image_origin_height?: Int64; // Original image height
  image_thumb_bytes?: Uint8Array; // Thumbnail data, max width/height 40
  image_thumb_mime?: string; // Thumbnail MIME type
  image_dominant_color?: string; // Dominant color of the image, in #ffffff format
}

/** File */
export interface File {
  file_id?: string; // File ID
  file_mime?: string; // File MIME type
  file_size?: Int64; // File size
  file_encryption?: Encryption; // File encryption
}

/** Encryption */
export interface Encryption {
  encryption_algorithm?: string; // Encryption algorithm
  encryption_key?: Uint8Array; // Encryption key
  encrypted_size?: Int64; // Encrypted size
}

/** Mentioned user */
export interface MessageTextMentionUser {
  user_id?: UserId; // User ID
  user_name?: string; // Username at the time of mention
  is_in_chat?: boolean; // Whether the user was in the chat at the time
}

/** User ID */
export interface UserId {
  user_id?: string; // User ID in the platform. The same user has the same user_id across all apps
  union_user_id?: string; // User ID within the same app group. The same user has the same union_user_id across different apps in the same group
  open_user_id?: string; // User ID within an app. The same user has different open_user_id values in different apps
}

export interface MessageTextEmoji {
  emoji_id?: string; // Emoji ID
  emoji_name?: string; // Emoji name at the time
}

/** Image message */
export interface MessageImage {
  image?: FileImage; // Image
}

/** Sticker message */
export interface MessageSticker {
  sticker?: Sticker; // Sticker
}

/** Sticker */
export interface Sticker {
  sticker_id?: string; // Sticker ID
  sticker_name?: string; // Sticker name
  sticker_name_i18n?: Record<string, string>; // Sticker internationalized name
  sticker_image?: FileImage; // Sticker image
}

/** Video message */
export interface MessageVideo {
  video?: FileVideo; // Video
}

/** Video file */
export interface FileVideo {
  video?: File; // Video
  video_width?: Int64; // Video width
  video_height?: Int64; // Video height
  video_duration?: number; // Video duration
  video_preview?: FileImage; // Video preview image
}

/** Audio message */
export interface MessageAudio {
  audio?: FileAudio; // Audio
}

/** Audio file */
export interface FileAudio {
  audio?: File; // Audio
  audio_duration?: number; // Audio duration
}

/** File message */
export interface MessageFile {
  file?: File; // File
  filename?: string; // Filename
}

/** User card message */
export interface MessageUserCard {
  user_id?: UserId; // User ID
}

/** Group card message */
export interface MessageGroupCard {
  chat_id?: string; // Chat ID
}

/** Group announcement */
export interface MessageGroupAnnouncement {
  message_text?: MessageText; // Announcement content
}

/** Card message */
export interface MessageCard {
  schema?: string; // Card schema version
  v1?: MessageCardV1; // V1
}

/** V1 */
export interface MessageCardV1 {
  header?: MessageCardV1Header; // Card header
  body?: MessageCardV1Body; // Card body
  footer?: MessageCardV1Footer; // Card footer
}

/** Card header */
export interface MessageCardV1Header {
  title?: string; // Title text
  title_i18n?: Record<string, string>; // Internationalized title text
  template?: string; // Title color template
}

/** Card body */
export interface MessageCardV1Body {
  message_text?: MessageText; // Card body text message
  message_text_i18n?: Record<string, MessageText>; // Internationalized card body text message
}

/** Card footer */
export interface MessageCardV1Footer {
  button_list?: MessageCardV1Button[]; // Button list
  button_align?: string; // Button alignment
}

/** Card button */
export interface MessageCardV1Button {
  button_text?: string; // Button text
  button_text_i18n?: Record<string, string>; // Internationalized button text
  template?: string; // Button style template, values: default, primary, danger, primary_text, danger_text, primary_filled, danger_filled
  link?: MessageCardV1ButtonLink; // Button link
}

/** Link */
export interface MessageCardV1ButtonLink {
  url?: string; // Default URL
  android_url?: string; // Android URL
  ios_url?: string; // iOS URL
  pc_url?: string; // Desktop URL
}

/** Message */
export interface Message {
  message_id?: string; // Message ID
  message_type?: string; // Message type
  message_status?: string; // Message status
  message_content?: MessageContent; // Message content
  message_created_at?: Int64; // Message creation time (milliseconds)
  chat_id?: string; // Chat ID
  chat_seq_id?: Int64; // Server-generated monotonically increasing ID at the chat level, used for ordering within a chat
  sender_id?: UserId; // Sender ID
  reply?: MessagePropReply; // Reply properties
}

/** Message reply properties */
export interface MessagePropReply {
  reply_message_id?: string; // ID of the message being replied to
}

/** Message received */
export interface EventMessageReceiveBody {
  message?: Message; // Message
}
